In [1]:
from scipy import stats
stats.norm.cdf(5,10,10) #left hand side to 5

np.float64(0.3085375387259869)

In [3]:
stats.norm.sf(15,10,10)

np.float64(0.3085375387259869)

In [5]:
#find area between 5 & 15
#1-cfd(5)-sf(15)

1-stats.norm.cdf(5,10,10)-stats.norm.sf(15,10,10)

np.float64(0.38292492254802624)

In [10]:
#mean score of GMAT exam is 680, SD is 40. What is the probability one student will score 750, 780

stats.norm.cdf(780,680,40)-stats.norm.cdf(750,680,40)

np.float64(0.033849491538040954)

In [11]:
# using SF
stats.norm.sf(750,680,40)-stats.norm.sf(780,680,40)

np.float64(0.033849491538040954)

In [9]:

#using 3rd formula
1-stats.norm.cdf(750,680,40)-stats.norm.sf(780,680,40)

np.float64(0.03384949153804098)

In [4]:
stats.norm.cdf(1,0,1)-stats.norm.cdf(-1,0,1)

np.float64(0.6826894921370859)

In [5]:
stats.norm.cdf(2,0,1)-stats.norm.cdf(-2,0,1)

np.float64(0.9544997361036416)

In [6]:
stats.norm.cdf(3,0,1)-stats.norm.cdf(-3,0,1)

np.float64(0.9973002039367398)

In [3]:
stats.norm.interval(0.95,400,5)

(np.float64(390.2001800772997), np.float64(409.7998199227003))

In [11]:
stats.norm.interval(0.95,400,25/(25 ** 0.5))

(np.float64(390.2001800772997), np.float64(409.7998199227003))

In [3]:
rainlist=[400,405,407,400,390,395,398,401,390,388]

In [10]:
import numpy as np

In [6]:
sample_mean=np.mean(rainlist)
print(sample_mean)

397.4

In [5]:
sample_sd=np.std(rainlist,ddof=1) 
print(sample_sd)
#ddof=1 std will be calculated for sample other it will be calculated for population

6.501281924871945

In [11]:
n=len(rainlist)
stats.t.interval(0.95,n-1,sample_mean,sample_sd / (n ** .5))

(np.float64(392.74926307726565), np.float64(402.0507369227343))

In [16]:
import numpy as np
from scipy import stats
rainlist=[400,405,407,400,390,395,398,401,390,388]

sample_mean=np.mean(rainlist)
print(sample_mean)
sample_sd=np.std(rainlist,ddof=1) 
print(sample_sd)
n=len(rainlist)
stats.t.interval(0.95,n-1,sample_mean,sample_sd / (n ** .5)) # pow(n,0.5)
moe=sample_mean/(n ** .5) #MOE = Measure of error 

print(moe)

397.4
6.501281924871945
125.66891421509138

In [34]:
sample=[1,98,98]
sample1=[1,1,98]
sample2=[1,5,5,6,7,8,8]

sample_skewness=stats.skew(sample,bias=False)
print(sample_skewness)
sample_skewness1=stats.skew(sample1,bias=False)
print(sample_skewness1)
sample_skewness2=stats.skew(sample2,bias=False)
print(sample_skewness2)

shape="right-skewed" if sample_skewness > 0 else "left-skewed" if sample_skewness<0 else "symmertic"
print(shape)

sample_kurtosis=stats.kurtosis(sample,fisher=True,bias=False)
print(f"Sample excess kurtosis: {sample_kurtosis}") #-v2 when pean less than normal distribution

sample_kurtosis1=stats.kurtosis(sample1,fisher=True,bias=False)
print(f"Sample excess kurtosis: {sample_kurtosis1}") #-v2 when pean less than normal distribution

sample_kurtosis2=stats.kurtosis(sample2,fisher=True,bias=False)
print(f"Sample excess kurtosis: {sample_kurtosis2}") #-v2 when pean less than normal distribution

-1.7320508075688772
1.7320508075688759
-1.2923289308413621
left-skewed
Sample excess kurtosis: -1.5
Sample excess kurtosis: -1.5000000000000004
Sample excess kurtosis: 1.985275754422477

In [42]:
rng=np.random.default_rng(42)
print(rng)
study_hours=rng.uniform(1,10,50)
print(study_hours)
exam_scores = 50 + 4 * study_hours + rng.normal(0,7,50)
print(exam_scores)
correlation=stats.pearsonr(study_hours,exam_scores).statistic

print(f"Pearson correlation:{correlation:.3f}")

Generator(PCG64)
[7.96560444 4.94990596 8.72738128 7.27631226 1.84759613 9.78060116
 7.85025732 8.07457875 2.15302269 5.05347344 4.33718222 9.3408849
 6.79478608 8.40485452 4.99072779 3.0451485  5.99126308 1.5743553
 8.44868055 6.68497959 7.82278966 4.19073371 9.73628222 9.03809009
 8.00545147 2.75174837 5.20048903 1.39423389 2.38860543 7.14744058
 7.7028594  9.70758759 3.93242822 4.33413735 5.2260023  2.70524223
 2.16929355 5.28134434 3.04218414 7.02832595 4.93436727 8.49410376
 7.30238592 3.81129977 8.49033821 8.24287922 4.48730541 3.59495294
 7.14245954 2.25777235]
[86.61481269 70.27267732 86.93336091 83.52426663 47.19029378 86.88470614
 78.10842069 77.82617005 56.68609502 80.67848294 61.28791106 94.14148808
 65.39905592 81.27522287 71.10218261 66.2841503  78.94363839 61.85085187
 81.35364669 73.50345582 87.29698981 65.42380458 80.01532461 78.21934987
 75.58563989 64.48711869 71.79893629 60.41033305 56.56365319 79.69954015
 85.19057037 86.66492459 68.92713956 62.70306783 68.36263228 58.14880367
 50.30629667 74.53418471 58.88292018 78.20076264 73.10269569 87.10213329
 83.86723943 64.5558007  80.99826467 82.41348939 56.13788061 54.25002443
 69.31094086 52.05036162]
Pearson correlation:0.888

In [3]:
stats.norm.cdf(60,62.8,1.4)

np.float64(0.022750131948179306)

In [13]:
stats.norm.cdf(-1.4)
print(stats.norm.cdf(-1.4)*2)

print(stats.norm.sf(1.4)*2)

0.16151331846754213
0.16151331846754213

In [12]:
#h0 
xbar=62.8
sigma=10
n=25
z=(xbar-60)/10*(pow(25,0.5))
print(z)

1.3999999999999986

In [20]:
#mu<=800
#mu>800
xbar=720
sigma=49
n=100
alpha=0.5

z=(xbar-800)/49*(pow(100,0.5))
print(z)
pvalue=stats.norm.sf(z)
print(pvalue)

-16.3265306122449
1.0

In [24]:
#ho:mu>=60
#h1mu<60

xbar=61.5
n=100
sigma=10
alpha=0.05

z=(xbar-60)/sigma*(pow(n,0.5))
print(z)
pvalue=stats.norm.cdf(z)
print(pvalue)

1.5
0.9331927987311419

In [28]:
#ho:s>=60
#h1: s<60

xbar=62.8
s=10
n=25
alpha=0.05

t=(xbar-60)/s*(pow(n,0.5))
print(t)
pvalue=stats.t.cdf(t,n-1)*2
print(pvalue)

1.3999999999999986
1.825691807788055

In [31]:
#mu<=800
#mu>800
xbar=720
s=49
n=100
alpha=0.5

t=(xbar-800)/s*(pow(n,0.5))
print(t)
pvalue=stats.t.sf(t,n-1)
print(pvalue)

-16.3265306122449
1.0

In [35]:
#ho:mu>=60
#h1mu<60

xbar=61.5
n=100
s=10
alpha=0.05

t=(xbar-60)/s*(pow(n,0.5))
print(t)
pvalue=stats.t.cdf(t,n-1)
print(pvalue)

1.5
0.9316015911420134

In [13]:
from statsmodels.stats.weightstats import ztest
from scipy import stats

import numpy as np

fill_volume = np.array([
    503, 505, 499, 504, 506, 502, 501, 507, 500, 504,
    503, 506, 502, 505, 504, 501, 508, 503, 505, 502,
    504, 506, 503, 501, 507, 504, 502, 505, 503, 506
])

print("n =", len(fill_volume))
print("Sample mean =", fill_volume.mean())

#type 1 mu=500 h1 mu!=500
#type 1 two sided 

#type1
z_stat, p_value=ztest(fill_volume,value=500, alternative="two-sided")
print(f"z statistics={z_stat:.4f}")
print(f"p-value={p_value:.4f}")
print()

#type 1 mu=500 h1 mu!=500
#type 1 two-sided type2 larger type3 smaller

#type2
z_stat, p_value=ztest(fill_volume,value=500, alternative="larger")
print(f"z statistics={z_stat:.4f}")
print(f"p-value={p_value:.4f}")
print()

#type3
z_stat, p_value=ztest(fill_volume,value=500, alternative="smaller")
print(f"z statistics={z_stat:.4f}")
print(f"p-value={p_value:.4f}")

n = 30
Sample mean = 503.7
z statistics=9.2137
p-value=0.0000

z statistics=9.2137
p-value=0.0000

z statistics=9.2137
p-value=1.0000

In [21]:

from scipy import stats

import numpy as np

fill_volume = np.array([
    503, 505, 499, 504, 506, 502, 501, 507, 500, 504,
    503, 506, 502, 505, 504, 501, 508, 503, 505, 502,
    504, 506, 503, 501, 507, 504, 502, 505, 503, 506
])

print("n =", len(fill_volume))
print("Sample mean =", fill_volume.mean())


#type 1 mu=500 h1 mu!=500
#type 1 two sided 

#type1
t_stat, p_value=stats.ttest_1samp(fill_volume,popmean=500, alternative="two-sided")
print(f"t statistics={t_stat:.4f}")
print(f"p-value={p_value:.4f}")
print()

#type 1 mu=500 h1 mu!=500
#type 1 two-sided type2 greater type3 less

#type2
t_stat, p_value=stats.ttest_1samp(fill_volume,popmean=500, alternative="greater")
print(f"t statistics={t_stat:.4f}")
print(f"p-value={p_value:.4f}")
print()

#type3
t_stat, p_value=stats.ttest_1samp(fill_volume,popmean=500, alternative="less")
print(f"t statistics={t_stat:.4f}")
print(f"p-value={p_value:.4f}")

n = 30
Sample mean = 503.7
t statistics=9.2137
p-value=0.0000

t statistics=9.2137
p-value=0.0000

t statistics=9.2137
p-value=1.0000

In [4]:
from statsmodels.stats.weightstats import ztest
from scipy import stats

import numpy as np

c=[2,-1,0,3,5]
cbar=np.mean(c)
s=np.std(c,ddof=1)
n=5

t_test=(cbar-0)/(s/pow(5,.5))
print("Probablitiy of density fucntion:",t_test)

pro=stats.t.sf(t_test,n-1)
print("Probablitiy of density fucntion::",pro)

#type3
t_stat, p_value=stats.ttest_1samp(c,popmean=0, alternative="greater")
print(f"t statistics={t_stat:.4f}")
print(f"p-value={p_value:.4f}\n")

after=[15,12,10,9,20]
before=[13,13,10,6,15]
t_stat, p_value=stats.ttest_rel(before,after, alternative="less")

print(f"t statistics={t_stat:.4f}")
print(f"p-value={p_value:.4f}")

Probablitiy of density fucntion: 1.6858544608470492
Probablitiy of density fucntion:: 0.08355165786629902
t statistics=1.6859
p-value=0.0836

t statistics=-1.6859
p-value=0.0836

In [39]:
#type3
t_stats=stats.t.sf(3.6,68)
pvalue=t_stats*2

print(t_stats)
print(pvalue)

0.0002998680006226332
0.0005997360012452664

In [14]:
import numpy as np
from scipy import stats
import pandas as pd


observed = np.array([100, 52, 48, 200])
expected = np.array([120, 160, 80, 40])

result = stats.chisquare(f_obs=observed, f_exp=expected)
print(result)

display(pd.DataFrame({
    "Defect type": ["A", "B", "C", "D"],
    "Observed": observed,
    "Expected": expected
}))
print(f"Chi-square statistic = {result.statistic:.4f}")
print(f"p-value = {result.pvalue:.4f}")
#print(pvalue_decision(result.pvalue))

#pvalue <5% -> h1 true which means the calim from the manager is incorrect

Power_divergenceResult(statistic=np.float64(729.0333333333333), pvalue=np.float64(1.0625059022443197e-157))

  Defect type  Observed  Expected
0           A       100       120
1           B        52       160
2           C        48        80
3           D       200        40

Chi-square statistic = 729.0333
p-value = 0.0000

In [18]:
contingency_table = pd.DataFrame(
    [[18, 82], [30, 70], [12, 88]],
    index=["Morning", "Evening", "Night"],
    columns=["Defective", "Not defective"]
)
display(contingency_table)

chi2, p_value, dof, expected = stats.chi2_contingency(contingency_table)

print(f"Chi-square statistic = {chi2:.4f}")
print(f"Degrees of freedom = {dof}")
print(f"p-value = {p_value:.4f}")
print(p_value>0.05)

#pvalue is less than .05, hence H1 is accepted, H0 rejected.abs

         Defective  Not defective
Morning         18             82
Evening         30             70
Night           12             88

Chi-square statistic = 10.5000
Degrees of freedom = 2
p-value = 0.0052
False

In [43]:
pg1 = np.array([2,2.5,2.7,2,1.9])
pg2 = np.array([3.1,2.9,2.5,3,3.2])
pg3 = np.array([1.6,.5,1.7,1,.8])

m1=pg1.mean()
print(m1)
m2=pg2.mean()
print(m2)
m3=pg3.mean()
print(m3)

sum1=0
for i in range(pg1.size):
    sum1=sum1+((pg1[i]-m1)**2)

print(sum1)

sum2=0
for i in range(pg2.size):
    sum2=sum2+((pg2[i]-m2)**2)

print(sum2)
sum3=0
for i in range(pg3.size):
    sum3=sum3+((pg3[i]-m3)**2)

print(sum3)

dwg=(sum1+sum2+sum3)/(12)
print("dwg:",dwg)

grand_mean=(2+2.5+2.7+2+1.9++3.1+2.9+2.5+3+3.2+1.6+.5+1.7+1+.8)/15

print("Grand mean:",grand_mean)

dbg=(5*(m1-grand_mean)**2 + 5*(m2-grand_mean)**2 +5*(m3-grand_mean)**2 )/2

print("dbg:",dbg)


test_stats=(dbg/dwg)
print("test statistics:",test_stats)

print("\n")


print(stats.f_oneway(pg1,pg2,pg3))

2.2199999999999998
2.94
1.1199999999999999
0.5080000000000002
0.29200000000000015
1.0679999999999998
dwg: 0.1556666666666667
Grand mean: 2.0933333333333333
dbg: 4.200666666666667
test statistics: 26.98501070663811


F_onewayResult(statistic=np.float64(26.985010706638146), pvalue=np.float64(3.622494426898301e-05))

# Plotting